### ISSUE TITLE
ActionViewSamplesFragment报错

### ISSUE THREAD

**Issue by zebraoo** [vejei/BottomNavigationBar#1]
java.lang.IllegalArgumentException: path must be convex
        at android.graphics.Outline.setConvexPath(Outline.java:284)
        at io.github.vejei.bottomnavigationbar.BottomNavigationBar$1.getOutline(BottomNavigationBar.java:144)
        at android.view.View.rebuildOutline(View.java:15020)
        at android.view.View.setBackgroundBounds(View.java:19561)
        at android.view.View.drawBackground(View.java:19526)
        at android.view.View.draw(View.java:19307)
        at io.github.vejei.bottomnavigationbar.BottomNavigationBar.draw(BottomNavigationBar.java:385)
        at android.view.View.updateDisplayListIfDirty(View.java:18239)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
        at android.view.View.updateDisplayListIfDirty(View.java:18230)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at android.view.View.draw(View.java:19330)
        at android.widget.ScrollView.draw(ScrollView.java:1739)
        at android.view.View.updateDisplayListIfDirty(View.java:18239)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at android.view.View.updateDisplayListIfDirty(View.java:18230)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at android.view.View.updateDisplayListIfDirty(View.java:18230)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at android.view.View.updateDisplayListIfDirty(View.java:18230)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at android.view.View.updateDisplayListIfDirty(View.java:18230)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at android.view.View.updateDisplayListIfDirty(View.java:18230)
        at android.view.View.draw(View.java:19037)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4297)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4083)
        at android.view.View.draw(View.java:19330)
        at com.android.internal.policy.DecorView.draw(DecorView.java:789)
        at android.view.View.updateDisplayListIfDirty(View.java:18239)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3117)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2926)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2464)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1446)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7014)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:916)
        at android.view.Choreographer.doCallbacks(Choreographer.java:728)
        at android.view.Choreographer.doFrame(Choreographer.java:660)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:902)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

setOutlineProvider(new ViewOutlineProvider() {
            @Override
            public void getOutline(View view, Outline outline) {
                 outline.setConvexPath(outlinePath);
            }
        });

**Comment by chen2030** [comment]
27 之前的问题
setOutlineProvider(new ViewOutlineProvider() {
            @Override
            public void getOutline(View view, Outline outline) {
                 if (outlinePath.isConvex()) {
                        outline.setConvexPath(outlinePath);
                  }
            }
        });

**Comment by chen2030** [comment]
API 27 之前的问题
 setOutlineProvider(new ViewOutlineProvider() {
            @Override
            public void getOutline(View view, Outline outline) {
                //添加判断
                    if (outlinePath.isConvex()) {
                        outline.setConvexPath(outlinePath);
                    }
            }
        });

**Comment by chenzz66** [comment]
API 27 之前的问题 >
 setOutlineProvider(new ViewOutlineProvider()   {

            @Override
            public void getOutline(View view, Outline outline) {
                //添加判断
                  if (outlinePath.isConvex()) {
                        outline.setConvexPath(outlinePath);
                  }
            }
        });
